" General
set encoding=utf-8
set fileencodings=utf-8
set t_Co=256
set ruler
set nocompatible
"set clipboard=unnamed " Mac OS X clipboard sharing

" Colors
colorscheme xoria256
syntax enable       " enable syntax processing

" Spaces and  Tabs
set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces
set shiftwidth=4    " the size of an 'indent'

" UI Config
set number          " show line numbers
set showcmd         " show command in bottom bar
set cursorline      " highlight current line
set laststatus=2    " always show statusline
set cmdheight=2     " height of the command bar
set showmatch       " highlight matching [{()}]
set textwidth=79
set colorcolumn=80 " - or + to put the marker to the left or right of textwidth
highlight ColorColumn ctermbg=lightgrey

" Search
set hlsearch        " highlight search terms
set incsearch       " find as you type search

" Filetype
filetype on
filetype plugin indent on

" Python
autocmd Filetype python set autoindent
autocmd Filetype python set smartindent

